[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "5000" }